### PR TITLE
Modify README.md

### PR DESCRIPTION
**Pull request by Mario-119**
Updated README.md with the latest community profiles submitted through the RetroNX Discord as of writing this. 

I've also omitted and deleted a couple of submitted profiles due to undesirable results whilst using them (frame drops, lag, etc.).

### CODE REVIEW

**Comment by m4xw** [comment]
Would you please report to us which profiles exactly where undesirable?
If so we will remove them from the channel.

**Comment by p-sam** [comment]
LGTM, thanks for the PR, would supersed #2 and #3

**Comment by p-sam** [comment]
@Mario-119 we'll merge this once you can tell us the deleted profiles, as per m4xw question, so we can sync it up with the discord channel

**Comment by Mario-119** [comment]
The Smash Ultimate profile seems to have frame drops while in battles with many particle and alpha effects, along with slowdown on the results screen. It seems like @5H00T4 has also mentioned this. 

Tetris 99 also seems to drop quite a lot of frames if you deviate from stock clocks at all. I've done quite a bit of testing on this, even with my own custom profiles.

I've also omitted profiles in which the individual who submitted them say that there is slowdown in certain aspects of the game but is mostly "fine". These profiles include Celeste, Yoshi's Crafted World, and Final Fantasy VII. I personally feel that the official profiles included in the database should not hamper the game in any fashion, but that's just me. Please feel free to ignore me if you disagree however. 

By the way, I just added the YouTube profile from the Discord (I wanted to do some extended testing with it first to make sure that videos did not drop any frames).

**Comment by p-sam** [comment]
Thanks.

Yeah, no problem for the YouTube profile, as we should mirror the profiles from Discord, and then either nuke them from both or keep them based on testing.

Also, I chose to keep the Celeste one, as it only slowdowns the map and does not impede gameplay

**Comment by p-sam** [comment]
merged in f35aa52

**Pull request closed without merging**
